In [145]:
import numpy as np
import numpy.linalg as la

Generate random data

In [146]:
data = np.arange(3000)
np.random.shuffle(data)
data = data.reshape(-1, 4)
print(data.shape)

(750, 4)


Set number of seeds, `k`

In [147]:
k = 4

Pick `k` initial seeds

In [148]:
seed_ind = np.random.choice(np.arange(data.shape[0]), k, replace=False)
print(f"Seeds: {seed_ind}")

print("Seeds:")
seeds = data[seed_ind, :]
print(seeds)

Seeds: [210 690 614  46]
Seeds:
[[2205 2342  329 2876]
 [2842  518 2924  994]
 [   9 2495 1520   60]
 [1920  317 1501 2300]]


Calculate distance from each sample to each seed

In [149]:
def distances(data, seeds):
    ds = [[la.norm(s - d) for s in seeds] for d in data]
    return np.array(ds)

For each datum in `data` find the seed to which it was the closest

In [150]:
def make_labels(data, seeds):
    ds = distances(data, seeds)
    labels = np.argmin(ds, axis=1)
    return labels

Calculate the new center of each cluster by averaging the seeds

In [151]:
def new_seeds(data, labels, k):
    inds = [np.argwhere(labels == _) for _ in range(k)]
    new_seeds = [np.mean(data[i, :], axis=0) for i in inds]
    return np.array(new_seeds)

Calculate new seeds until convergence

In [152]:
labels = make_labels(data, seeds)
seeds = new_seeds(data, labels, k)

In [153]:
conv_count = 0
old_seeds = np.zeros_like(seeds)
while not(np.allclose(seeds, old_seeds)):
    conv_count += 1
    old_seeds = np.copy(seeds)
    labels = make_labels(data, seeds)
    seeds = new_seeds(data, labels, k)

I will define goodness of clustering as the sum of the squared distance of each sample to its seed

In [157]:
def error(data, seeds, labels):
    e = 0
    for _ in range(labels.shape[0]):
        l = labels[_]
        e += la.norm(data[_] - seeds[l])**2
    return e

In [159]:
error(data, seeds, labels)

1355571287.999357

In [160]:
a = np.array([3, 3])
b = np.array([1, 1])
la.norm(a-b)

2.8284271247461903

In [164]:
np.sqrt(np.sum((a - b) ** 2))

2.8284271247461903