In [4]:
import pandas as pd
import numpy as np
import numpy.linalg as la

In [2]:
datafile = "../data/processed/UTK-peers_processed.csv"
df = pd.read_csv(datafile)

In [3]:
df.head()

Unnamed: 0                            Name    IPEDS#  % Blk Total Students  \
0           0  Univ. of Tennessee - Knoxville  221759.0              6.625965   
1           1                Univ. of Georgia  139959.0              8.048713   
2           2                    Purdue Univ.  243780.0              2.994663   
3           3                Texas A&M Univ.   228723.0              3.203109   
4           4            Michigan State Univ.  171100.0              6.591080   

   % Hisp Total Students  2017 US News top 65  Total Enroll  % Grad Enroll  \
0               3.404561                   46         27845      21.483211   
1               4.732909                   18         36130      23.755882   
2               4.128780                   20         40472      24.491006   
3              19.193581                   27         63813      23.277389   
4               4.020737                   33         50538      22.547390   

   Six-year graduation rate  ACT/ SAT Avg       ...         \
0                        70          27.0       ...          
1                        85          27.5       ...          
2                        75          26.5       ...          
3                        79          26.0       ...          
4                        77          25.5       ...          

   Student Services Expenditures  Endowment Figure  Endowment per Student FTE  \
0                   30587.112868         782734414               30587.112868   
1                   27830.636107         939024216               27830.636107   
2                   66375.581533        2445541926               66375.581533   
3                  180613.450122       10521034492              180613.450122   
4                   55180.107179        2549137018               55180.107179   

   Total Faculty.1  Total Tenure /Tenure-Track Facutly.1  Carm R1_1  \
0             1526                                  1117          1   
1             1918                                  1606          1   
2             1783                                  1700          1   
3             2983                                  1995          1   
4             2616                                  1811          1   

   Carm R1_2  2014 Med School_pre clin  2014 Med School_x  Vet School_True  
0          0                         0                  0                1  
1          0                         0                  0                1  
2          0                         0                  0                1  
3          0                         1                  0                1  
4          0                         0                  1                1  

[5 rows x 64 columns]

In [ ]:
class KMeans():
    def __init__(self):
        self.k = None
        self.iterations = None
        self.labels = None
        self.seeds = None
    
    def fit(self, data, k, iterations=10):
        # Pick k random rows as seeds for clusters
        indices = np.arange(data.shape[0])
        seed_indices = np.random.choice(indices, size=k, replace=False)
        self.seeds = data[seed_indices, :]
        
        distances = np.zeros(data.shape[0], k)
        
        # Make an array of labels
        labels = np.random.randint(0, k, size=indices.shape[0])
        
        # Copy those labels to old_labels
        old_labels = np.copy(labels)
        
        # calculate distance to each seed
        for i in range(k):
            s = self.seeds[i]
            distances[:, i] = self.calc_dist(i)
        
        labels = np.argmin(distances, axis=1)
            
        while labels != old_labels:
            
    
    def distance(self, x1, x2):
        return la.norm(x1 - x2)**2
    
    def calc_dist(self, row):
        d = [self.distance(row, seed) for seed in self.seeds]
        d = np.array(d)

In [35]:
a = np.arange(16.)
np.random.shuffle(a)
a = a.reshape((-1, 2))
print(a)

[[13. 12.]
 [ 2. 11.]
 [15.  8.]
 [10.  7.]
 [ 9.  6.]
 [ 3.  0.]
 [ 4.  1.]
 [ 5. 14.]]


In [40]:
k = 2
indices = np.arange(a.shape[0])

In [41]:
seed_indices = np.random.choice(indices, size=k, replace=False)

In [42]:
seed_indices

array([2, 3])

In [43]:
seeds = a[seed_indices, :]
print(seeds)

[[15.  8.]
 [10.  7.]]


In [45]:
distances = np.zeros((a.shape[0], k))
print(distances)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [46]:
labels = np.random.randint(0, k, size=indices.shape[0])
print(labels)

[1 0 0 0 0 1 1 1]


In [48]:
old_labels = np.copy(labels)
print(old_labels)

[1 0 0 0 0 1 1 1]


In [50]:
def distance(row, seed):
    return la.norm(row - seed) ** 2
def calc_dist(seeds, row):
    d = [distance(row, seed) for seed in seeds]
    d = np.array(d)

In [52]:
for sample in a:
    for i in range(k):
        s = seeds[i]
        distances[:, i] = calc_dist(s, a)
print(distances)

[[nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]]
