In [1]:
import numpy.linalg as la
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [32]:
x1 = np.random.choice(np.arange(100), 5).astype(np.float64)
x2 = np.random.choice(np.arange(100), 5).astype(np.float64)
x3 = np.random.choice(np.arange(100), 5).astype(np.float64)
x = np.hstack([x1.reshape((-1, 1)), x2.reshape((-1, 1)), x3.reshape((-1, 1))])

In [33]:
x

array([[34., 21., 33.],
       [63.,  3., 74.],
       [97., 34., 15.],
       [33., 26., 15.],
       [21., 96.,  8.]])

In [34]:
scaler = StandardScaler().fit(x)
xs = scaler.transform(x)

In [35]:
pca = PCA().fit(xs)

In [36]:
u, s, vt = la.svd(xs, full_matrices=False)
v = vt.T

In [37]:
s**2 / np.sum(s**2)

array([0.6405317 , 0.27017014, 0.08929817])

In [38]:
pca.explained_variance_ratio_

array([0.6405317 , 0.27017014, 0.08929817])

In [39]:
pca.components_[0]

array([-0.44702145,  0.66097075, -0.60273501])

In [40]:
vt[0]

array([ 0.44702145, -0.66097075,  0.60273501])

In [41]:
pca.transform(xs)

array([[-0.15933327, -0.63439329,  0.38409448],
       [-2.03816921, -0.64197333, -0.52949811],
       [-0.46211422,  1.76536232, -0.00960881],
       [ 0.41380492, -0.27535983,  0.74812866],
       [ 2.24581179, -0.21363587, -0.59311622]])

In [42]:
u * s

array([[ 0.15933327,  0.63439329, -0.38409448],
       [ 2.03816921,  0.64197333,  0.52949811],
       [ 0.46211422, -1.76536232,  0.00960881],
       [-0.41380492,  0.27535983, -0.74812866],
       [-2.24581179,  0.21363587,  0.59311622]])

In [43]:
xs @ vt.T[:,0]

array([ 0.15933327,  2.03816921,  0.46211422, -0.41380492, -2.24581179])