In [3]:
import numpy.linalg as la
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [49]:
x1 = np.random.choice(np.arange(100), 5)
x2 = np.random.choice(np.arange(100), 5)
x3 = np.random.choice(np.arange(100), 5)
x = np.hstack([x1.reshape((-1, 1)), x2.reshape((-1, 1)), x3.reshape((-1, 1))])

In [122]:
x

array([[59, 64, 71],
       [75, 80, 55],
       [94, 64,  1],
       [44, 36, 74],
       [12, 85, 40]])

In [127]:
scaler = StandardScaler().fit(x)
xs = scaler.transform(x)

/Users/jrpowers-luhn/miniconda3/envs/cs528p2/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/jrpowers-luhn/miniconda3/envs/cs528p2/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [116]:
pca = PCA().fit(xs)

In [117]:
u, s, vt = la.svd(xs)
v = vt.T

In [118]:
s**2 / np.sum(s**2)

array([0.49523097, 0.37321142, 0.1315576 ])

In [119]:
pca.explained_variance_ratio_

array([0.49523097, 0.37321142, 0.1315576 ])

In [120]:
pca.components_[0]

array([ 0.53979708,  0.39396753, -0.74391444])

In [121]:
v[0]

array([0.53979708, 0.62965788, 0.55870391])

In [124]:
vec = x[0]
vec

array([59, 64, 71])

In [131]:
pca.transform(xs)

array([[-0.63749441, -0.17087215,  0.56450712],
       [ 0.48855938,  0.22073715,  0.9445083 ],
       [ 2.00049932, -0.83913219, -0.49164215],
       [-1.65627258, -1.10613871, -0.46767688],
       [-0.19529172,  1.8954059 , -0.54969639]])

In [130]:
u[:, :3] * s

array([[-0.63749441,  0.17087215,  0.56450712],
       [ 0.48855938, -0.22073715,  0.9445083 ],
       [ 2.00049932,  0.83913219, -0.49164215],
       [-1.65627258,  1.10613871, -0.46767688],
       [-0.19529172, -1.8954059 , -0.54969639]])

In [136]:
u @ np.vstack([np.diag(s), np.zeros((2, 3))])

array([[-0.63749441,  0.17087215,  0.56450712],
       [ 0.48855938, -0.22073715,  0.9445083 ],
       [ 2.00049932,  0.83913219, -0.49164215],
       [-1.65627258,  1.10613871, -0.46767688],
       [-0.19529172, -1.8954059 , -0.54969639]])

In [138]:
u2, s2, vt2 = la.svd(x, full_matrices=False)

In [140]:
u2

array([[-0.49098253,  0.24314   ,  0.21899718],
       [-0.5450888 , -0.06911033,  0.00662384],
       [-0.43288508, -0.81565437, -0.00796998],
       [-0.37684757,  0.40703868,  0.51463695],
       [-0.36388292,  0.32424398, -0.82890388]])

In [141]:
u2 * s2

array([[-110.40966079,   17.52616182,   10.97909172],
       [-122.57680395,   -4.98165215,    0.33207629],
       [ -97.34500033,  -58.79448324,   -0.39956304],
       [ -84.74356976,   29.34040385,   25.80054429],
       [ -81.82814603,   23.37234728,  -41.55584074]])

In [142]:
u2 @ np.diag(s2)

array([[-110.40966079,   17.52616182,   10.97909172],
       [-122.57680395,   -4.98165215,    0.33207629],
       [ -97.34500033,  -58.79448324,   -0.39956304],
       [ -84.74356976,   29.34040385,   25.80054429],
       [ -81.82814603,   23.37234728,  -41.55584074]])