In [1]:
import numpy.linalg as la
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
x1 = np.random.choice(np.arange(100), 5)
x2 = np.random.choice(np.arange(100), 5)
x3 = np.random.choice(np.arange(100), 5)
x = np.hstack([x1.reshape((-1, 1)), x2.reshape((-1, 1)), x3.reshape((-1, 1))])

In [3]:
x

array([[56, 42, 88],
       [54, 80, 13],
       [19, 32,  1],
       [ 7, 16, 91],
       [61, 44, 23]])

In [4]:
scaler = StandardScaler().fit(x)
xs = scaler.transform(x)

/Users/jrpl/miniconda3/envs/cs528p2/lib/python3.7/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/jrpl/miniconda3/envs/cs528p2/lib/python3.7/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [5]:
pca = PCA().fit(xs)

In [15]:
u, s, vt = la.svd(xs, full_matrices=False)
v = vt.T

In [16]:
s**2 / np.sum(s**2)

array([0.65445577, 0.272946  , 0.07259824])

In [17]:
pca.explained_variance_ratio_

array([0.65445577, 0.272946  , 0.07259824])

In [18]:
pca.components_[0]

array([-0.58438983, -0.66758406,  0.46132424])

In [19]:
vt[0]

array([-0.58438983, -0.66758406,  0.46132424])

In [13]:
pca.transform(xs)

array([[ 0.12198483, -1.37963768,  0.09821404],
       [-1.92841063,  0.13150293, -0.66076607],
       [ 0.37757002,  1.46615567,  0.18516807],
       [ 2.28283714, -0.10133698, -0.32958361],
       [-0.85398136, -0.11668393,  0.70696758]])

In [25]:
u * s

array([[ 0.12198483,  1.37963768,  0.09821404],
       [-1.92841063, -0.13150293, -0.66076607],
       [ 0.37757002, -1.46615567,  0.18516807],
       [ 2.28283714,  0.10133698, -0.32958361],
       [-0.85398136,  0.11668393,  0.70696758]])

In [31]:
xs @ vt.T[:,0]

array([ 0.12198483, -1.92841063,  0.37757002,  2.28283714, -0.85398136])